#%RAML 0.8
---
title: OmicronAPI
baseUri: http://omicron/api/{version}
version: v1
mediaType: application/json
schemas:
  - 404: !include schemas/404.json
    users: !include schemas/users.json
    users_post: !include schemas/users_post.json
    users_response: !include schemas/users.json
    user: !include schemas/user.json


/users:
    displayName: List of users in the system
    get:
        description: Get list of users
        queryParameters:
            contains:
                displayName: Contains
                type: string
                description: |
                    Allows searching of user names by a string. Returns
                    users with name matching the string
            starts_with:
                displayName: Starts With
                type: string
                description: Search by begins with string
            ends_with:
                displayName: Ends with
                type: string
                description: Search by end
            page:
                displayName: Page
                type: integer
                description: page number of list
            items_per_page:
                displayName: Items Per Page
                type: integer
                description: display required number of users per page
        responses:
            200:
                body:
                    application/json:
                        schema: users
    post:
        description: Create a new user. Check the schema against the JSON schema for validation.
        body:
            application/json:
                schema: UserPost
        responses:
            200:
                description: Successful creation of a new user
                body:
                    application/json:
                        schema: users_response
            400:
                description: Bad request, user may already exist, or the data supplied is incorrect
                body:
                    application/json:
                        schema: !include schemas/users_400.json
    /schema:
        get:
            description: Get schema used to display users
            responses:
                200:
                    application/json:
                        schema: users
    /{userId}:
        uriParameters:
            userId:
                type: integer
        /schema:

/files:
    /schema:
    /{fileId}:
        uriParameters:
            fileId:
                type: integer
        /schema:

/projects:
    get:
        description: Retrieve a list of projects
    post:
        description: Create a new project
    /schema:
        get:
            description: Return the JSON schema for this 
    /{projectId}:
        uriParameters:
            projectId:
                type: integer
        /schema:
        /files:
        /users: